#:schema node_modules/wrangler/config-schema.json

name = "storefront-template-test-cfbuilds"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Assets directory for static files
assets = { directory = ".open-next/assets", binding = "ASSETS" }
